name: Minichat CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Copy file .env
      run: cp .env.example .env
    - name: Build the minichat app
      run: docker-compose build app
    - name: Run the minichat app
      run: docker-compose up -d
    - name: Install dependencies
      run: docker exec minichat-app npm install
    - name: Build resource
      run: | 
        docker exec minichat-app npm run resource:complie
        docker exec minichat-app npm run build:css
        docker exec minichat-app npm run storage:link
    - name: Start server
      run: docker exec minichat-app node ./bin/test
      
